package examples.exceptions;

//import examples.exceptions.*;

public class Assignment1 {
	
	public static void CalcFeeTest() {
		int credits;
		double bill;
		
		try {
			credits = 13;
			bill = MyLibrary.CalcFee(credits);
			System.out.format("The bill for %d credits is %f \n", credits, bill);
		}
		catch (CreditException cex) {
			System.out.println(cex.getMessage());
		}
		
		try {
			credits = 5;
			bill = MyLibrary.CalcFee(credits);
			System.out.format("The bill for %d credits is %f \n", credits, bill);
		}
		catch (CreditException cex) {
			System.out.println(cex.getMessage());
		}
		
		try {
			credits = 34;
			bill = MyLibrary.CalcFee(credits);
			System.out.format("The bill for %d credits is %f \n", credits, bill);
		}
		catch (CreditException cex) {
			System.out.println(cex.getMessage());
		}
		
		try {
			credits = 13;
			bill = MyLibrary.CalcFee(credits);
			System.out.format("The bill for %d credits is %f \n", credits, bill);
		}
		catch (CreditException cex) {
			System.out.println(cex.getMessage());
		}
		
	}
	
	public static void FactorialTest() {
		int in;
		long out;
		
		try {
			in = 5;
			out = MyLibrary.Fac(in);
			System.out.format("%d factorial is %d \n", in, out);
		}
		catch (NotAValidIntegerException nex) {
			System.out.println(nex.getMessage());
		}
		
		try {
			in = -5;
			out = MyLibrary.Fac(in);
			System.out.format("%d factorial is %d \n", in, out);
		}
		catch (NotAValidIntegerException nex) {
			System.out.println(nex.getMessage());
		}
		
		try {
			in = 25;
			out = MyLibrary.Fac(in);
			System.out.format("%d factorial is %d \n", in, out);
		}
		catch (NotAValidIntegerException nex) {
			System.out.println(nex.getMessage());
		}

	}

	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		MyLibrary ml = new MyLibrary();
		CalcFeeTest();
		FactorialTest();
	}

}
